# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: dbmgmthon
  pool: 5
  timeout: 5000
  socket: /var/run/mysqld/mysqld.sock
  username: root

production:
  adapter: mysql2
  database: dbmgmt_contract
  username: dbmgmt_contract
  password: dTCF8F23BAD9Pbsv
  pool: 5
  timeout: 500
  socket: /var/run/mysqld/mysqld.sock
